# Generated by Django 3.0.5 on 2020-06-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppapp', '0002_hensu1_hensu2_hensu3_hensu4_hensu5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hensu1',
            new_name='vlue',
        ),
    ]
