# Generated by Django 3.0.5 on 2020-06-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppapp', '0003_auto_20200626_0530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vlue',
            new_name='hensu1',
        ),
    ]
