# Generated by Django 3.0.5 on 2020-06-27 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppapp', '0004_auto_20200626_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hensu1',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hensu2',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hensu3',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hensu4',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hensu5',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='hensu',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
